// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7qtuMxA_SY_zWaD8LfP-qJd__pBZc_4Y',
    appId: '1:25302970174:web:6d89255479902287f3466f',
    messagingSenderId: '25302970174',
    projectId: 'campus-connect-ea94f',
    authDomain: 'campus-connect-ea94f.firebaseapp.com',
    storageBucket: 'campus-connect-ea94f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJVNZvf8zMP2Mm3s04NTKphc_4g1mfcms',
    appId: '1:25302970174:android:8dbb261297af3ec3f3466f',
    messagingSenderId: '25302970174',
    projectId: 'campus-connect-ea94f',
    storageBucket: 'campus-connect-ea94f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4_wdm7-quP-gyyXCZNAjfh4XbdOrOjzI',
    appId: '1:25302970174:ios:65c2e9dd59c6f8e7f3466f',
    messagingSenderId: '25302970174',
    projectId: 'campus-connect-ea94f',
    storageBucket: 'campus-connect-ea94f.appspot.com',
    iosBundleId: 'com.example.campusConnect',
  );
}
